config/routes.rb
Rails.application.routes.draw do
  # Devise
  devise_for :users, controllers: { 
    registrations: "users/registrations",
    sessions: "users/sessions"
  }
  devise_for :admin_users, ActiveAdmin::Devise.config

  # Active Admin
  ActiveAdmin.routes(self)

  # Root
  authenticated :user do
    root to: "users#show", as: :authenticated_root
  end

  unauthenticated :user do
    root to: "pages#home", as: :user
    root to: "pages#home"
  end

  # Products
  resources :products, only: [:show] do
    resources :droplets, only: [:show], as: :droplet
  end
  post 'products/:id/follow', to: 'products#follow', as: :follow_product, constraints: { format: 'json' }
  post 'products/:id/unfollow', to: 'products#unfollow', as: :unfollow_product, constraints: { format: 'json' }

  # Droplets
  resources :droplets, only: [] do
    resources :comments, only: [:create, :update, :destroy]
  end

  # Search
  get '/search', to: "search#index", as: :search

  # Dragonfly
  get '/products/:id/thumb/:style.:format' => Dragonfly.app.endpoint { |params, app|
    Product.find(params[:id]).vanity_safe.image.thumb(params[:style]).encode(params[:format])
  }, as: :product_thumb
end

app/models/droplet.rb
class Droplet < Content
  extend FriendlyId

  acts_as_votable

  has_many :comments

  friendly_id :slug_candidates, :use => [:slugged, :finders]

  def comment_hash
    comments.includes(:user).hash_tree
  end

  def update_cached_comments_total!
    self.update_attribute(:cached_comments_total, comments.count)
  end

  private

  def should_generate_new_friendly_id?
    new_record? || slug.blank?
  end
end

app/models/droplet_type.rb
class DropletType < ActiveRecord::Base
  extend FriendlyId

  has_many :droplets

  validates_presence_of :name, :icon
  validates_uniqueness_of :name

  friendly_id :name, :use => [:slugged, :finders]

  # Must be use in a join with droplets
  def self.with_counts
    select("droplet_types.*").
    select("count(contents.id) OVER (PARTITION BY droplet_types.slug) AS type_count")
  end
end

app/controllers/droplets_controller.rb
class DropletsController < ApplicationController

  def show
    @title = "Rivyr: #{product.name} comments"
    @droplet_cell = cell(:droplet, droplet)
    @comment = Comment.new
    @comments = droplet.comment_hash
    @sidebar_cells = [
      cell(:product_actions, @product).show(current_user: current_user),
    ]
  end

  private

  def droplet
    @droplet ||= product.stream.find_by_slug!(params[:id])
  end

  def product
    @product ||= Product.find(params[:product_id])
  end
end

app/views/droplets/show.html.slim
div class=("row #{controller_name} #{action_name}") 
  == cell(:sidebar, @sidebar_cells).show(current_user: current_user, title: @product.name)
  .col-xs-12.col-sm-9.comments
    == @droplet_cell.mast
    - if user_signed_in?
      = form_for [@droplet, @comment], html: { class: 'col-xs-12' } do |f|
        = f.text_area :body, class: 'col-xs-12', rows: 4
        = f.submit "submit", class: 'pull-right'
    - else
      .box.col-xs-12
        span>= link_to "Log In to comment", product_droplet_path(@product, @droplet, force_auth: true) 
    #comments.col-xs-12.col-sm-9
      == cell(:comment_thread, @comments)