config/routes.rb
Rails.application.routes.draw do
  # Devise
  devise_for :users, controllers: { 
    registrations: "users/registrations",
    sessions: "users/sessions"
  }
  devise_for :admin_users, ActiveAdmin::Devise.config

  # Active Admin
  ActiveAdmin.routes(self)

  # Root
  authenticated :user do
    root to: "users#show", as: :authenticated_root
  end

  unauthenticated :user do
    root to: "pages#home", as: :user
    root to: "pages#home"
  end

  # Products
  resources :products, only: [:show] do
    resources :droplets, only: [:show], as: :droplet
  end
  post 'products/:id/follow', to: 'products#follow', as: :follow_product, constraints: { format: 'json' }
  post 'products/:id/unfollow', to: 'products#unfollow', as: :unfollow_product, constraints: { format: 'json' }

  # Droplets
  resources :droplets, only: [] do
    resources :comments, only: [:create, :update, :destroy]
  end

  # Search
  get '/search', to: "search#index", as: :search

  # Dragonfly
  get '/products/:id/thumb/:style.:format' => Dragonfly.app.endpoint { |params, app|
    Product.find(params[:id]).vanity_safe.image.thumb(params[:style]).encode(params[:format])
  }, as: :product_thumb
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    @q = params[:q] || ""
    @title = "Rivyr: Search for #{@q}"

    query = {}
    query[:facets] = ['category'.freeze]
    query[:tagFilters] = params[:category] if params[:category]
    
    response = Product.rivyr_raw(@q, query)

    @products = Product.where(id: response['hit_ids'.freeze]).includes(:vanity)
    @facets = response['facets'.freeze]

    @sidebar_cells = [
      cell(:facet_set, current_user).show(path: search_path, params_key: :category, filters: FacetSet.new(@facets['category'], ProductCategory), q: @q)
    ]
  end
end

app/views/search/index.slim
div class=("row #{controller_name} #{action_name}") 
  == cell(:sidebar, @sidebar_cells).show(current_user: current_user, title: "Search Results")
  .col-xs-12.col-sm-9.results
    ul.col-xs-12
      - @products.each_with_index do |product, index|
        = link_to product_path(product)
          li class="col-xs-12 col-sm-12  #{'last' if (index + 1) % 3 == 0}"
              .media-left
                = image_tag product.vanity_safe.image.thumb('30x30').url
              .media-body
                p= product.name